name: Deploy Portfolio to Web Server

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create deployment package
      run: |
        echo "Preparing files for deployment..."
        ls -la
        
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /domains/zanganehai.com/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          .gitignore
          README.md
          .github/**
          *.md
          
    - name: Deploy via SFTP (Alternative)
      if: failure() # Try SFTP if FTP fails
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /domains/zanganehai.com/public_html/
        remote_host: ${{ secrets.SFTP_HOST }}
        remote_user: ${{ secrets.SFTP_USERNAME }}
        remote_key: ${{ secrets.SFTP_PRIVATE_KEY }}
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful! Portfolio updated at https://srv637-files.hstgr.io/54b7d1bc1ec58d94/files/public_html/"
        else
          echo "❌ Deployment failed. Check the logs above."
        fi
